import { Proponent } from './proponent';
import { CurrentPhase } from './currentphase';
import { News } from './news';

export class Project {
  _id: number;
  code: string;
  name: string;
  proponent: Proponent;
  description: string;
  status: string;
  type: string;
  sector: string;
  openCommentPeriod: string;
  eacDecision: string;
  CEAAInvolvement: string;
  CEAALink: string;
  decisionDate: Date;
  currentPhase: CurrentPhase;
  region: string;
  location: string;
  latitude: number;
  longitude: number;
  projectLead: string;
  projectLeadEmail: string;
  projectLeadPhone: string;
  responsibleEPD: string;
  responsibleEPDEmail: string;
  responsibleEPDPhone: string;
  CELead: string;
  CELeadEmail: string;
  CELeadPhone: string;
  constructor(obj?: any) {
    this._id = (obj && obj._id) || null;
    this.code = (obj && obj.code) || null;
    this.name = (obj && obj.name) || null;
    this.description = (obj && obj.description) || null;
    this.proponent = (obj && obj.proponent && new Proponent(obj.proponent)) || null;
    this.status = (obj && obj.status) || null;
    this.type = (obj && obj.type) || null;
    this.sector = (obj && obj.sector) || null;
    this.openCommentPeriod = (obj && obj.openCommentPeriod) || null;
    this.eacDecision = (obj && obj.eacDecision) || null;
    this.CEAAInvolvement = (obj && obj.CEAAInvolvement) || null;
    this.CEAALink = (obj && obj.CEAALink) || null;
    this.decisionDate = (obj && obj.decisionDate) || null;
    this.currentPhase = (obj && obj.currentPhase && new CurrentPhase(obj.currentPhase)) || null;
    this.region = (obj && obj.region) || null;
    this.location = (obj && obj.location) || null;
    this.latitude = (obj && obj.lat) || 0;
    this.longitude = (obj && obj.lon) || 0;
    this.projectLead = (obj && obj.projectLead) || null;
    this.projectLeadPhone = (obj && obj.projectLeadPhone) || null;
    this.projectLeadEmail = (obj && obj.projectLeadEmail) || null;
    this.responsibleEPD = (obj && obj.responsibleEPD) || null;
    this.responsibleEPDPhone = (obj && obj.responsibleEPDPhone) || null;
    this.responsibleEPDEmail = (obj && obj.responsibleEPDEmail) || null;
    this.CELead = (obj && obj.CELead) || null;
    this.CELeadPhone = (obj && obj.CELeadPhone) || null;
    this.CELeadEmail = (obj && obj.CELeadEmail) || null;
  }
}
